version: "3.7"

services:

  backend:
    image: backend
    container_name: backend
    restart: always
    build:
      context: ./backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend